FROM python:3.9 AS builder
LABEL maintainer="gontrum@me.com and ejschoen@i2kconnect.com"
LABEL version="0.3"
LABEL description="Base image, containing no language models."

# Install the required packages
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    supervisor \
    curl \
    nginx && \
    apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin

# Install node for the frontend
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash - && \
  apt-get install -y nodejs &&\
  apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin

# Copy and set up the app
COPY . /app

# Build SASSC
RUN bash /app/build_sassc.sh

# Build app
RUN cd /app/frontend && make clean && make
RUN cd /app && make -f Makefile.llm clean && make -f Makefile.llm


FROM python:3.9
LABEL maintainer="gontrum@me.com and ejschoen@i2kconnect.com"
LABEL version="0.3"
LABEL description="Base image, containing no language models."

# Install the required packages
RUN apt-get update && apt-get install -y \
    supervisor \
    curl \
    nginx \
    nfs-common && \
    apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin

COPY --from=builder /app /app
COPY --from=builder /usr/bin/sassc /usr/bin/sassc
COPY --from=builder /usr/bin/node /usr/bin/node

# Configure nginx & supervisor
RUN mv /app/config/nginx.conf /etc/nginx/sites-available/default &&\
  echo "daemon off;" >> /etc/nginx/nginx.conf && \
  mv /app/config/supervisor.conf /etc/supervisor/conf.d/

WORKDIR /app
ENV PORT 80
EXPOSE 80
CMD ["bash", "/app/start.sh"]

